[package]
name = "lolcate-rs"
version = "0.1.0"
authors = ["Nicolas Girard <girard.nicolas@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0"
toml = "0.4"
serde_derive = "1.0"
serde = "1.0"
lz4 = "1"
clap = "2"
regex = "1"
ignore = "0.4"
walkdir = "2"
termcolor = "1"
lazy_static = "1.3"

[[bin]]
path = "src/main.rs"
name = "lolcate"
