[package]
name = "lolcate-rs"
version = "0.1.0"
authors = ["Nicolas Girard <girard.nicolas@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0"
toml = "0.4"
serde_derive = "1.0"
serde = "1.0"
walkdir = "2"
lz4 = "1"
clap = "2"
#lazy_static = "1.2.0"
regex = "1"
